export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      roles: {
        Row: {
          id: string;
          name: "super_admin" | "admin" | "teacher" | "parent";
          display_name: string;
          description: string | null;
          is_system_role: boolean;
          status: "active" | "inactive" | "archived";
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      permissions: {
        Row: {
          id: string;
          module: string;
          action: string;
          scope: string;
          key: string;
          description: string | null;
          is_system_permission: boolean;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      role_permissions: {
        Row: {
          id: string;
          role_id: string;
          permission_id: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      user_profiles: {
        Row: {
          id: string;
          branch_id: string | null;
          role_id: string;
          full_name: string;
          email: string;
          phone: string | null;
          avatar_document_id: string | null;
          status: "pending" | "active" | "suspended" | "disabled" | "archived";
          last_login_at: string | null;
          preferences: Json;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
          deleted_by: string | null;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      students: {
        Row: {
          id: string;
          branch_id: string | null;
          student_number: string;
          first_name: string;
          last_name: string;
          full_name: string;
          date_of_birth: string;
          gender: "female" | "male" | "other" | "prefer_not_to_say" | null;
          primary_language: string | null;
          school_name: string | null;
          photo_document_id: string | null;
          medical_notes: string | null;
          emergency_notes: string | null;
          status: "active" | "inactive" | "archived";
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          branch_id?: string | null;
          student_number: string;
          first_name: string;
          last_name: string;
          full_name: string;
          date_of_birth: string;
          gender?: "female" | "male" | "other" | "prefer_not_to_say" | null;
          primary_language?: string | null;
          school_name?: string | null;
          photo_document_id?: string | null;
          medical_notes?: string | null;
          emergency_notes?: string | null;
          status?: "active" | "inactive" | "archived";
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
        };
        Update: {
          id?: string;
          branch_id?: string | null;
          student_number?: string;
          first_name?: string;
          last_name?: string;
          full_name?: string;
          date_of_birth?: string;
          gender?: "female" | "male" | "other" | "prefer_not_to_say" | null;
          primary_language?: string | null;
          school_name?: string | null;
          photo_document_id?: string | null;
          medical_notes?: string | null;
          emergency_notes?: string | null;
          status?: "active" | "inactive" | "archived";
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
        };
        Relationships: [];
      };
      parent_student_relationships: {
        Row: {
          id: string;
          student_id: string;
          parent_id: string | null;
          parent_full_name: string;
          parent_email: string | null;
          parent_phone: string | null;
          relationship_type: "mother" | "father" | "guardian" | "grandparent" | "other";
          is_primary_contact: boolean;
          can_pick_up: boolean;
          receives_invoices: boolean;
          receives_announcements: boolean;
          status: "active" | "inactive" | "archived";
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          student_id: string;
          parent_id?: string | null;
          parent_full_name: string;
          parent_email?: string | null;
          parent_phone?: string | null;
          relationship_type: "mother" | "father" | "guardian" | "grandparent" | "other";
          is_primary_contact?: boolean;
          can_pick_up?: boolean;
          receives_invoices?: boolean;
          receives_announcements?: boolean;
          status?: "active" | "inactive" | "archived";
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
        };
        Update: {
          id?: string;
          student_id?: string;
          parent_id?: string | null;
          parent_full_name?: string;
          parent_email?: string | null;
          parent_phone?: string | null;
          relationship_type?: "mother" | "father" | "guardian" | "grandparent" | "other";
          is_primary_contact?: boolean;
          can_pick_up?: boolean;
          receives_invoices?: boolean;
          receives_announcements?: boolean;
          status?: "active" | "inactive" | "archived";
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
        };
        Relationships: [];
      };
      emergency_contacts: {
        Row: {
          id: string;
          student_id: string;
          full_name: string;
          relationship: string;
          phone: string;
          alternate_phone: string | null;
          priority: number;
          notes: string | null;
          status: "active" | "inactive" | "archived";
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          student_id: string;
          full_name: string;
          relationship: string;
          phone: string;
          alternate_phone?: string | null;
          priority?: number;
          notes?: string | null;
          status?: "active" | "inactive" | "archived";
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
        };
        Update: {
          id?: string;
          student_id?: string;
          full_name?: string;
          relationship?: string;
          phone?: string;
          alternate_phone?: string | null;
          priority?: number;
          notes?: string | null;
          status?: "active" | "inactive" | "archived";
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
        };
        Relationships: [];
      };
      student_medical_profiles: {
        Row: {
          id: string;
          student_id: string;
          doctor_name: string | null;
          doctor_phone: string | null;
          insurance_provider: string | null;
          policy_number: string | null;
          medical_conditions: string | null;
          medication_notes: string | null;
          dietary_requirements: string | null;
          emergency_medical_consent: boolean;
          visibility: "management" | "teacher_limited" | "parent_visible";
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          student_id: string;
          doctor_name?: string | null;
          doctor_phone?: string | null;
          insurance_provider?: string | null;
          policy_number?: string | null;
          medical_conditions?: string | null;
          medication_notes?: string | null;
          dietary_requirements?: string | null;
          emergency_medical_consent?: boolean;
          visibility?: "management" | "teacher_limited" | "parent_visible";
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
        };
        Update: {
          id?: string;
          student_id?: string;
          doctor_name?: string | null;
          doctor_phone?: string | null;
          insurance_provider?: string | null;
          policy_number?: string | null;
          medical_conditions?: string | null;
          medication_notes?: string | null;
          dietary_requirements?: string | null;
          emergency_medical_consent?: boolean;
          visibility?: "management" | "teacher_limited" | "parent_visible";
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
        };
        Relationships: [];
      };
      student_allergies: {
        Row: {
          id: string;
          student_id: string;
          allergen: string;
          severity: "unknown" | "mild" | "moderate" | "severe";
          reaction: string | null;
          treatment: string | null;
          notes: string | null;
          status: "active" | "inactive" | "archived";
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          student_id: string;
          allergen: string;
          severity?: "unknown" | "mild" | "moderate" | "severe";
          reaction?: string | null;
          treatment?: string | null;
          notes?: string | null;
          status?: "active" | "inactive" | "archived";
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
        };
        Update: {
          id?: string;
          student_id?: string;
          allergen?: string;
          severity?: "unknown" | "mild" | "moderate" | "severe";
          reaction?: string | null;
          treatment?: string | null;
          notes?: string | null;
          status?: "active" | "inactive" | "archived";
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
        };
        Relationships: [];
      };
      student_status_history: {
        Row: {
          id: string;
          student_id: string;
          from_status: "active" | "inactive" | "archived" | null;
          to_status: "active" | "inactive" | "archived";
          reason: string | null;
          changed_at: string;
          changed_by: string | null;
        };
        Insert: {
          id?: string;
          student_id: string;
          from_status?: "active" | "inactive" | "archived" | null;
          to_status: "active" | "inactive" | "archived";
          reason?: string | null;
          changed_at?: string;
          changed_by?: string | null;
        };
        Update: {
          id?: string;
          student_id?: string;
          from_status?: "active" | "inactive" | "archived" | null;
          to_status?: "active" | "inactive" | "archived";
          reason?: string | null;
          changed_at?: string;
          changed_by?: string | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
